apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i3cqfu2hw-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:9756d5895a5e0ba75df07a09e52fd11195264297@sha256:9ad2f8a9a9b977d4e67fdddd3e6f3a86b9f6256e2833118bae8ebffef7694cdd
          name: container-image
